apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  ports:
    - protocol: TCP
      port: 31001
      targetPort: nodejs-port
  selector:
    app: helloworld
  type: LoadBalancer
